name: Manual API-Test

on:
  workflow_dispatch:

jobs:
  schemathesis:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v6
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag juice-shop:latest

    - name: Start juice-shop
      run: docker run --rm -p 3000:3000 juice-shop:latest
    
    - name: Static code analysis of the OpenAPI Spec using schemathesis
      uses: schemathesis/action@v2
      with:
        schema: "http://localhost:3000/openapi.json"
